config/routes.rb
Rails.application.routes.draw do
  resources :registers

   root 'welcome#index'

   resources :login
  match "/check", :to => "registers#check", :via => [:get, :post]

end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
  def show
    @sample = "Ext.data.JsonP.someCallback({
    users: [
        {
            id: 1,
            name: 'Ed Spencer',
            email: 'ed@sencha.com'
        }
    ]
});"
    render json: @sample, :content_type => 'application/javascript'
  end
  def create
    @sample = "{name: 'Max', email:' m@m.com'}"
    render json: @sample, :content_type => 'application/javascript'
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy ]
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin']= '*'
    headers['Access-Control-Allow-Methods']= 'POST, GET, OPTIONS'
    headers['Access-Control-Max-Age']='17280000'
  end


  def cors_preflight_check
    headers['Access-Control-Allow-Origin']= '*'
    headers['Access-Control-Allow-Methods']= 'POST, GET, OPTIONS'
    headers['Access-Control-Request-Method']='*'
    headers['Access-Control-Allow-Headers']= '*'
  end

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  def check
    #@register = Register.find(:email=>params[:email], :password=>params[:password]);
    @registers = Register.where("email = ? AND password = ?", params[:email], params[:password]);
    #@register = Register.where(:email => params[:email]).find(:passwd => params[:password]);

    respond_to do |format|
      if @registers.any?
        #format.html { redirect_to @register, notice: 'Register was successfully created.' }
        #format.json { render :show, status: :created, location: @register }
        format.json { render json: @register, status: :created, location: @register }
      else
        format.html { render :new }
        #format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end


  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    #@register = Register.new(register_params)
    @register = Register.new(:name => params[:name], :hospitalID => params[:hospID], :email => params[:email],
                             :password => params[:passwd], :lname =>params[:lname], :gender =>params[:gender],
                             :dateofbirth =>params[:bday])


    respond_to do |format|
      if @register.save
        #format.html { redirect_to @register, notice: 'Register was successfully created.' }
        #format.json { render :show, status: :created, location: @register }
        format.json { render json: @register, status: :created, location: @register }
      else
        #format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:name, :hospitalID, :email, :password, :lname, gender)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hospitalID %><br>
    <%= f.text_field :hospitalID %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<h1>Listing registers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>lname</th>
      <th>Hospitalid</th>
      <th>Email</th>
      <th>Password</th>
      <th>Birthdate</th>
      <th>Gender</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.name %></td>
        <td><%= register.lname %></td>
        <td><%= register.hospitalID %></td>
        <td><%= register.email %></td>
        <td><%= register.password %></td>
        <td><%= register.dateofbirth %></td>
        <td><%= register.gender %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @register.name %>
</p>


<p>
  <strong>Hospitalid:</strong>
  <%= @register.hospitalID %>
</p>

<p>
  <strong>Email:</strong>
  <%= @register.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @register.password %>
</p>


<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>

app/views/welcome/index.html.erb
<h2> This is my Project App </h2>
<p>
  The time is now: <%=Time.now%>
</p>